# Shiftly Message Configuration
# Uses legacy color codes (&c = red, &a = green, &e = yellow, etc.)
# Format codes: &l bold, &o italic, &n underline, &m strikethrough, &k magic, &r reset

messages:
  no_permission: "&c&lYou don't have permission."
  usage_move: "&e&oUsage: &r/move &7<player|@a> <server>"
  usage_move_group: "&e&oUsage: &r/move -group &7<group> <server>"
  player_not_found: "&cPlayer not found."
  server_not_found: "&cServer not found."
  moved_success: "&a&lPlayer:&r &f<player> &7moved &a-> &f<server>"
  moved_group_success: "&a&lGroup:&r &f<group> &7moved &a-> &f<server>"

settings:
  # Message broadcast mode

  # GLOBAL - Everyone on the proxy will see the message
  # TARGET_ONLY - Only the moved player will see the message
  # TARGET_AND_ADMINS - The moved player + players with admin permission will see the message

  message_scope: "GLOBAL"
